[versions]
kotlin = "1.9.21"
lwjgl = "3.3.3"
slf4j = "2.0.9"
annotations = "24.1.0"
kotlinter = "4.1.0"
textile = "2.0.1"
dokka = "1.9.10"

# Markdown
minemark = "1.0-SNAPSHOT94"
commonmark = "0.21.0"
tagsoup = "1.2.1"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
licenser = { id = "org.quiltmc.gradle.licenser", version.ref = "textile" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
git_hooks = { id = "com.github.jakemarsden.git-hooks", version = "0.0.2" }

[libraries]
lwjgl = { module = "org.lwjgl:lwjgl", version.ref = "lwjgl" }
lwjgl-nanovg = { module = "org.lwjgl:lwjgl-nanovg", version.ref = "lwjgl" }
lwjgl-opengl = { module = "org.lwjgl:lwjgl-opengl", version.ref = "lwjgl" }
lwjgl-stb = { module = "org.lwjgl:lwjgl-stb", version.ref = "lwjgl" }
lwjgl-glfw = { module = "org.lwjgl:lwjgl-glfw", version.ref = "lwjgl" }

slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }

kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }
dokka_base = { module = "org.jetbrains.dokka:dokka-base", version.ref = "dokka" }

# Markdown
minemark = { module = "dev.dediamondpro:minemark-core", version.ref = "minemark" }
commonmark = { module = "org.commonmark:commonmark", version.ref = "commonmark" }
commonmark_ext_striketrough = { module = "org.commonmark:commonmark-ext-gfm-strikethrough", version.ref = "commonmark" }
commonmark_ext_tables = { module = "org.commonmark:commonmark-ext-gfm-tables", version.ref = "commonmark" }
tagsoup = { module = "org.ccil.cowan.tagsoup:tagsoup", version.ref = "tagsoup" }

[bundles]
lwjgl = ["lwjgl", "lwjgl-nanovg", "lwjgl-opengl", "lwjgl-stb", "lwjgl-glfw"]
slf4j = ["slf4j-api", "slf4j-simple"]
kotlin = ["kotlin-stdlib", "kotlin-annotations"]
markdown = ["minemark", "commonmark", "commonmark_ext_striketrough", "commonmark_ext_tables", "tagsoup"]
